package com.arkiv.player.data.plugin

import org.json.JSONArray
import org.json.JSONObject
import java.security.MessageDigest

/** [NuvioPluginConverter.convert]'s result: a ready-to-ship `plugin.js` + `kino-plugin.json` pair. */
data class NuvioConversionResult(val script: String, val manifestJson: String, val hosts: List<String>, val warnings: List<String>)

/**
 * Turns one Nuvio scraper into a Kino plugin (spec §5): the compat shim ([PluginPrelude.nuvioShim])
 * + the scraper's own source, byte for byte, + a small adapter mapping Nuvio's
 * `getStreams(tmdbId, type, season, episode)` onto Kino's `search`/`resolve` (spec §6). Pure and
 * offline -- every network call (fetching the scraper's raw `.js`, the optional `domains.json`)
 * happens in `NuvioPluginInstaller`, before this runs.
 *
 * The generated manifest always names the literal `"plugin.js"` as its `entry`: that file never
 * existed upstream (this converter builds it fresh), so whoever installs the result must write the
 * generated bytes under that name -- `PluginAddress.rawUrl(manifest.entry)` must NOT be used to
 * locate it, since it never exists at that URL. The original scraper's own path
 * ([NuvioScraperEntry.filename]) is only ever fetched separately, as input to [convert].
 */
object NuvioPluginConverter {
    /** cheerio calls that walk the DOM: [PluginHtml]'s flat match list has no tree to walk, so these have no translation (see `nuvio-shim.js`). */
    private val CHEERIO_TRAVERSAL = Regex("""\.(parent|next|siblings|closest)\s*\(""")

    fun convert(
        scraper: NuvioScraperEntry,
        scraperSource: String,
        repoSlug: String,
        extraHosts: List<String>,
        tmdbApiKey: String,
    ): NuvioConversionResult {
        val slug = scraper.id.lowercase().replace(Regex("[^a-z0-9-]"), "-").trim('-').ifEmpty { "scraper" }
        val hash = sha256Hex(repoSlug.toByteArray(Charsets.UTF_8)).take(6)
        // The hash disambiguates the same scraper id across two different Nuvio repos: its space is
        // reserved FIRST, so a long slug is what shrinks -- capping the whole "nuvio-<slug>-<hash>"
        // string at PluginManifest's 40-char id limit from the right would otherwise truncate into
        // (or entirely erase) the hash for a sanitized slug of ~34+ characters.
        val idPrefix = "nuvio-"
        val idSuffix = "-$hash"
        val maxSlugLen = (40 - idPrefix.length - idSuffix.length).coerceAtLeast(1)
        val id = idPrefix + slug.take(maxSlugLen).trimEnd('-').ifEmpty { "s" } + idSuffix

        val hosts = (NuvioHostExtractor.extractHosts(scraperSource) + extraHosts)
            .distinct()
            .take(ManifestParser.MAX_HOSTS)

        val warnings = buildList {
            if (CHEERIO_TRAVERSAL.containsMatchIn(scraperSource)) {
                add("Este scraper usa funciones de cheerio que podrían no traducirse del todo (.parent()/.next()/.siblings()/.closest()).")
            }
            if (hosts.size >= ManifestParser.MAX_HOSTS) {
                add("Se detectaron 20 o más dominios; algunos podrían faltar (tope de hosts de Kino).")
            }
        }

        val shim = PluginPrelude.nuvioShim.replace("__NUVIO_TMDB_API_KEY__", tmdbApiKey)
        val script = shim + "\n\n" + scraperSource + "\n\n" + ADAPTER

        val manifestJson = JSONObject()
            .put("id", id).put("name", scraper.name).put("version", "1.0.0").put("apiVersion", 1)
            .put("entry", "plugin.js")
            .put(
                "description",
                "Convertido automáticamente desde el plugin de Nuvio \"${scraper.name}\" ($repoSlug). " +
                    "Licencia GPL-3.0 del código original. Los hosts se detectaron automáticamente y podrían estar incompletos.",
            )
            .put("hosts", JSONArray(hosts))
            .put("capabilities", JSONArray(listOf("search", "resolve")))
            .toString()

        return NuvioConversionResult(script, manifestJson, hosts, warnings)
    }

    private fun sha256Hex(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

    /**
     * `getStreams(tmdbId, type, season, episode)` -> `search`/`resolve`. Nuvio has no query-based
     * search of its own (only tmdbId + type + season/episode), so `search` never really searches: it
     * hands back exactly one item that just encodes those four fields for `resolve` to decode later.
     * `resolve` calls the wrapped `getStreams` and picks the first result that isn't torrent-only
     * (Kino's sandbox has no BitTorrent client, spec §6.2) -- `kino.error("unavailable", …)` otherwise.
     *
     * `ref` normally arrives as the JSON string `search` built (Kino quotes an item's `ref` before
     * calling `resolve` with it -- see `PluginContentSource.resolve`), but a plain object is accepted
     * too: nothing about this adapter's own contract requires the string encoding, only Kino's
     * particular caller does.
     */
    private val ADAPTER = """

        var __nuvioGetStreams = module.exports.getStreams;

        export async function search(query) {
          if (!query.tmdbId) return [];
          return [{
            id: query.tmdbId + "-" + query.type + "-" + query.season + "-" + query.episode,
            ref: JSON.stringify({ tmdbId: query.tmdbId, type: query.type, season: query.season, episode: query.episode }),
            title: query.q || query.originalTitle || "",
            kind: "movie",
          }];
        }

        export async function resolve(ref) {
          var r = (typeof ref === "string") ? JSON.parse(ref) : ref;
          var streams = (await __nuvioGetStreams(r.tmdbId, r.type, r.season, r.episode)) || [];
          var playable = streams.filter(function (s) { return s && s.url && !s.infoHash; });
          if (!playable.length) throw kino.error("unavailable", "solo torrents o sin resultados");
          var best = playable[0];
          return { url: best.url, headers: best.headers, mime: best.mime };
        }
    """.trimIndent()
}
