package com.arkiv.player.data.plugin

import org.json.JSONArray
import org.json.JSONObject
import java.security.MessageDigest

/**
 * [NuvioPluginConverter.convert]'s result: a ready-to-ship `plugin.js` + `kino-plugin.json` pair.
 * [hosts] is what the manifest declares (TMDB always first); [scraperHosts] only what was detected in
 * the scraper and its remote domain list (all of them, even any the manifest's 16 KB cap left out of
 * [hosts]) -- empty means the scraper names no site.
 */
data class NuvioConversionResult(
    val script: String,
    val manifestJson: String,
    val hosts: List<String>,
    val warnings: List<String>,
    val scraperHosts: List<String>,
)

/**
 * A real library of Nuvio's own runtime (its providers README, "Available Modules", plus the `Buffer`
 * real scrapers use), vendored unmodified under `resources/plugin/nuvio-vendor/` ([file]; its header
 * says which npm version and how it was built). A generated script carries one only when the
 * scraper's source [needs] it: cheerio alone is ~190 KB that QuickJS parses on every sandbox load.
 * [binding] is what the library needs declared in the module scope after it (Node's `Buffer` global).
 */
internal enum class NuvioLibrary(val file: String, private val trigger: Regex, val binding: String = "") {
    // Any mention: `require("cheerio-without-node-native")`, its `cheerio`/`react-native-cheerio` aliases.
    CHEERIO("cheerio.js", Regex("cheerio")),
    // Also any `crypto.subtle` use or Node `crypto` module: the shim computes SHA-384 (and PBKDF2
    // beyond what kino.crypto takes) with it.
    CRYPTO_JS("crypto-js.js", Regex("""crypto-js|\bsubtle\b|$NODE_CRYPTO""")),
    // The global (`Buffer.from(...)`) or the module; never `ArrayBuffer`/`messageBuffer` (no word boundary).
    // Node's `crypto` module (the shim's) answers in Buffers, so naming it needs Buffer too.
    BUFFER("buffer.js", Regex("""\bBuffer\b|["'`]buffer["'`]|$NODE_CRYPTO"""), binding = "var Buffer = __nuvioLibBuffer.Buffer;\n");

    fun needs(scraperSource: String): Boolean = trigger.containsMatchIn(scraperSource)
}

/** A quoted `crypto` / `node:crypto` module name: `require("crypto")`, `import ... from "node:crypto"`. */
private const val NODE_CRYPTO = """["'`](?:node:)?crypto["'`]"""

/**
 * Turns one Nuvio scraper into a Kino plugin (spec §5): the compat shim ([PluginPrelude.nuvioShim])
 * + the real libraries the scraper can `require` ([NuvioLibrary]) + the scraper's own source, byte
 * for byte but wrapped in its own IIFE, + a small adapter mapping Nuvio's
 * `getStreams(tmdbId, mediaType, season, episode)` onto Kino's `search`/`resolve` (spec §6).
 * Pure and offline -- every network call (fetching the scraper's raw `.js`, the optional
 * `domains.json`) happens in `NuvioPluginInstaller`, before this runs.
 *
 * The whole result loads as ONE ES module (`PluginRuntime.open`'s `js.addModule`), so the shim's own
 * top-level `module`/`exports`/`require`/`fetch` and the scraper's own top-level code can't just be
 * concatenated at the same top level: two top-level declarations of the same name in one module
 * scope make QuickJS reject the WHOLE script with `SyntaxError: invalid redefinition of global
 * identifier` -- and a bundled/minified scraper redeclaring one of those four names is common. The
 * scraper's source instead runs inside an isolating IIFE with its own private `module`/`exports`
 * (exposed to the adapter as `__nuvioModuleExports`), so its own top-level declarations only ever
 * SHADOW the shim's in a nested scope -- never a redefinition, never an error. A scraper that
 * declares its own top-level `require` does lose access to the shim's `require('cheerio')` etc.
 * from inside its own body (shadowed), but that's rare in practice and far better than the hard
 * syntax error this replaces. The vendored libraries sit between the shim and the scraper: each is
 * an esbuild IIFE defining one `__nuvioLib*` module-scope variable, evaluated after the shim has
 * declared what one of them reads at load time (crypto-js's random source) and before the scraper's
 * top level `require`s them.
 *
 * The generated manifest always names the literal `"plugin.js"` as its `entry`: that file never
 * existed upstream (this converter builds it fresh), so whoever installs the result must write the
 * generated bytes under that name -- `PluginAddress.rawUrl(manifest.entry)` must NOT be used to
 * locate it, since it never exists at that URL. The original scraper's own path
 * ([NuvioScraperEntry.filename]) is only ever fetched separately, as input to [convert].
 */
object NuvioPluginConverter {
    /**
     * The plugin id a scraper of [repoSlug] (the resolved repo address, `InstalledRecord.nuvioRepo`)
     * converts to: the same on every device, so a synced row can be checked against it.
     */
    fun idFor(scraperId: String, repoSlug: String): String {
        val slug = scraperId.lowercase().replace(Regex("[^a-z0-9-]"), "-").trim('-').ifEmpty { "scraper" }
        val hash = sha256Hex(repoSlug.toByteArray(Charsets.UTF_8)).take(6)
        // The hash disambiguates the same scraper id across two different Nuvio repos: its space is
        // reserved FIRST, so a long slug is what shrinks -- capping the whole "nuvio-<slug>-<hash>"
        // string at PluginManifest's 40-char id limit from the right would otherwise truncate into
        // (or entirely erase) the hash for a sanitized slug of ~34+ characters.
        val idPrefix = "nuvio-"
        val idSuffix = "-$hash"
        val maxSlugLen = (40 - idPrefix.length - idSuffix.length).coerceAtLeast(1)
        return idPrefix + slug.take(maxSlugLen).trimEnd('-').ifEmpty { "s" } + idSuffix
    }

    fun convert(
        scraper: NuvioScraperEntry,
        scraperSource: String,
        repoSlug: String,
        remoteHosts: NuvioRemoteHosts = NuvioRemoteHosts.NONE,
    ): NuvioConversionResult {
        val id = idFor(scraper.id, repoSlug)

        // Every validated host the scraper names is declared (a manifest has no host-count limit
        // since 0.9.45; the 16 KB manifest cap is the only bound, see the size check below), in
        // priority order: the remote list's entries this scraper names (its current, rotated domain),
        // then the literals that look like its OWN site ([NuvioHostExtractor.primaryHosts]: an
        // address-named constant, or a URL with a query built at runtime), then its other literals,
        // then the rest of a shared remote list. A bundle lists its shared hoster resolvers first and
        // its entry module last (cuevanaubd names 98 hosts, its API host `cuevana.unbuendato.com`
        // near the end), so without this the consent sheet's folded view would show resolvers, not
        // the site the person is actually installing -- and the priority order is also what decides
        // which hosts go first should the list ever not fit the manifest's byte cap.
        val literals = NuvioHostExtractor.extractHosts(scraperSource)
        val primary = NuvioHostExtractor.primaryHosts(scraperSource).toSet()
        val (ownSite, rest) = literals.partition { it in primary }
        val candidates = (remoteHosts.preferred + ownSite + rest + remoteHosts.others)
            .filter(NuvioHostExtractor::isPlausibleHost)
            .distinct()
        // TMDB is the ADAPTER's own dependency (every search's artwork, every series' episode list),
        // so it always holds the first slot whatever the scraper names.
        val allHosts = listOf(TMDB_HOST) + (candidates - TMDB_HOST)

        // Never Kino's own TMDB key in plain: the script carries a marker the runtime swaps for it only
        // on requests to TMDB (see TMDB_KEY_MARKER), so a third-party scraper can't read or send it anywhere.
        val shim = PluginPrelude.nuvioShim.replace("__NUVIO_TMDB_API_KEY__", TMDB_KEY_MARKER)
        val libraries = NuvioLibrary.entries.filter { it.needs(scraperSource) }
            .joinToString("") { PluginPrelude.nuvioVendor(it.file) + "\n" + it.binding + "\n" }
        // The scraper's own top-level code runs inside an IIFE, never spliced in at the same top
        // level as the shim: see this object's KDoc for why (QuickJS module-scope collisions).
        // Its `console` is the adapter's recording one (see ADAPTER's __nuvioConsole), handed in
        // through an outer function so the scraper's own scope may still declare a `console` of its own.
        val wrapped = "var __nuvioModuleExports = (function (console) { return (function () {\n" +
            "var module = { exports: {} };\n" +
            "var exports = module.exports;\n" +
            NuvioAsyncStart.defer(scraperSource) +
            "\nreturn module.exports;\n})(); })(__nuvioConsole);\n"
        // The scraper's own declared types and display name, baked in for the adapter's support check.
        val displayName = scraper.name.trim().ifEmpty { scraper.id }
        val supportBinding = "\nvar __NUVIO_SUPPORTED_TYPES = " +
            // Folded once here onto movie/tv/anime (NuvioMediaTypes, the picker's own sets): `series` must mean tv.
            JSONArray(scraper.supportedTypes.map(NuvioMediaTypes::canonical).distinct()).toString() + ";\n" +
            "var __NUVIO_SCRAPER_NAME = " + JSONObject.quote(displayName) + ";\n"
        val script = shim + "\n\n" + libraries + CONSOLE + wrapped + supportBinding + ADAPTER

        fun manifestFor(hosts: List<String>, warnings: List<String>): String = JSONObject()
            // Clipped to ManifestParser's own name limit: a longer Nuvio scraper name would otherwise make the whole manifest invalid.
            .put("id", id).put("name", scraper.name.trim().take(ManifestParser.MAX_NAME_CHARS).trim().ifEmpty { scraper.id.take(ManifestParser.MAX_NAME_CHARS) })
            .put("version", VERSION).put("apiVersion", ManifestParser.STREAM_HOSTS_API_VERSION)
            .put("entry", "plugin.js")
            .put("description", description(scraper.name, repoSlug, warnings))
            .put("hosts", JSONArray(hosts))
            // "download": a converted scraper's movies and episodes may be saved for offline viewing (the
            // consent sheet shows the line; an existing install gets it through "Buscar actualización").
            .put("capabilities", JSONArray(listOf("search", "episodes", "resolve", "download")))
            // Nuvio scrapers return videos from CDNs that change per title: the person approves "any video host" once, at install.
            .put("streamHosts", ManifestParser.LIVE_STREAM_HOSTS_ANY)
            // Their resolvers hop across mirror and CDN hosts no scan can list: kino.fetch may reach
            // any PUBLIC host, approved once, instead of one dialog per new host.
            .put("fetchHosts", ManifestParser.LIVE_STREAM_HOSTS_ANY)
            .toString()

        // The only bound on the declared list is the manifest's own byte cap (ManifestParser.MAX_BYTES,
        // ~700 typical domains): a scraper naming even more keeps its highest-priority ones (the order
        // above), with a warning on the consent sheet. What's left out is still reachable through
        // fetchHosts "any" and the reactive approval.
        var hosts = allHosts
        var warnings = emptyList<String>()
        var manifestJson = manifestFor(hosts, warnings)
        while (hosts.size > 1 && manifestJson.toByteArray(Charsets.UTF_8).size > ManifestParser.MAX_BYTES) {
            hosts = hosts.dropLast(1)
            warnings = listOf("Aviso: se detectaron demasiados dominios; ${allHosts.size - hosts.size} quedaron fuera.")
            manifestJson = manifestFor(hosts, warnings)
        }

        return NuvioConversionResult(script, manifestJson, hosts, warnings, scraperHosts = candidates)
    }

    /**
     * What the converter itself produces, as a number: bump it whenever the conversion output changes
     * (the shim, the adapter, a vendored library, the generated manifest's shape). An update never
     * needs it -- [NuvioPluginInstaller.checkUpdate] compares the script's hash -- but it goes into
     * [VERSION], so "Buscar actualización" and Ajustes show a new version for a new conversion.
     * 0 was every conversion before it existed ("1.0.0"); 1 is apiVersion 4, fetchHosts any, the
     * series adapter and the TMDB key behind a marker; 2 is the typed search (no tmdbId) answered
     * from TMDB's own search.
     */
    const val CONVERTER_REVISION = 2

    /**
     * A converted plugin's `version`: `1.<CONVERTER_REVISION>.0`. The upstream scraper's own changes
     * don't move it (they are found by hash, and Nuvio's own `version` fields are not reliable).
     */
    const val VERSION = "1.$CONVERTER_REVISION.0"

    /** The one host the adapter itself calls (`search` artwork, `episodes`); see [convert]. */
    const val TMDB_HOST = "api.themoviedb.org"

    /** The name [tmdbKeySecrets]' marker answers to in `kino.secret` (the shim never asks for it). */
    const val TMDB_KEY_SECRET = "tmdbApiKey"

    /**
     * What a converted plugin carries as `TMDB_API_KEY` instead of Kino's own key. URL-safe, so it
     * survives `encodeURIComponent` and JSON unchanged. A runtime of a converted plugin
     * ([tmdbKeySecrets]) substitutes the real key for it only in a request to [TMDB_HOST] (https),
     * refuses a request carrying it anywhere else, and redacts the key from everything that comes
     * back -- the sealed-secret mechanism ([PluginSecrets.plain]).
     */
    const val TMDB_KEY_MARKER = "__kinoSecret_tmdbApiKey_nuvio__"

    /** The secrets a runtime of a plugin converted from Nuvio opens with: Kino's TMDB key, toward TMDB only. Null without a key. */
    fun tmdbKeySecrets(tmdbApiKey: String?): PluginSecrets? =
        tmdbApiKey?.takeIf { it.isNotEmpty() }?.let { PluginSecrets.plain(TMDB_KEY_SECRET, TMDB_KEY_MARKER, it, listOf(TMDB_HOST)) }

    /**
     * The consent sheet shows `description` as is, so the [warnings] ride in it: the spec wants them
     * seen BEFORE installing, and this way the sheet itself needs no change. Built to fit
     * [ManifestParser.MAX_DESCRIPTION_CHARS] (the parser silently truncates past it): origin +
     * license first, then every warning, and only then the generic "hosts were auto-detected" caveat
     * -- the one part dropped when it doesn't fit. [name]/[repoSlug] are clipped so the head plus the
     * one warning there can be (too many hosts for the manifest's byte cap) always fit (≤ 137 + 1 + 65 chars).
     */
    private fun description(name: String, repoSlug: String, warnings: List<String>): String {
        val max = ManifestParser.MAX_DESCRIPTION_CHARS
        val head = "Convertido desde el plugin de Nuvio \"${name.take(30)}\" (${repoSlug.take(40)}); código original GPL-3.0."
        val tail = "Los hosts se detectaron automáticamente y podrían estar incompletos."
        val body = (listOf(head) + warnings).joinToString(" ")
        return if (body.length + 1 + tail.length <= max) "$body $tail" else body.take(max)
    }

    private fun sha256Hex(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

    /**
     * Nuvio's `getStreams(tmdbId, mediaType, season, episode)` -> Kino's `search`/`episodes`/`resolve`.
     * Nuvio has no catalogue or text search of its own, only that call, so the titles come from TMDB
     * (with the TMDB key the shim already carries):
     *
     * - `search` with a TMDB id answers ONE item for the TMDB id Kino asks about, with TMDB's poster, backdrop, year
     *   and synopsis when TMDB answers (one call, given 4 s of the search's 15: without it the item
     *   still comes back, bare, instead of the whole search timing out on optional artwork). A series
     *   with no episode chosen is a `series` item, so Kino opens its season/episode list like any
     *   other source's. A query that already names the episode (Kino's refine flow) or a movie is a
     *   `movie` item that plays straight away; only a real movie carries `ids.tmdb`, because Kino
     *   enriches a movie-kind item from TMDB's `/movie/<id>` and an episode's id is a show's.
     * - `search` WITHOUT a TMDB id (a typed search: the TV's "Ir", "Ver otras fuentes" by text, an
     *   anime card) but with a `q` asks TMDB's own search instead -- `/search/multi`, or
     *   `/search/movie` / `/search/tv` when the scraper only has one of them or Kino asked for a
     *   series -- in one request (8 s of the search's 15), and answers up to 10 matches shaped
     *   exactly like the TMDB-id items above (same `id`/`ref`), ranked by `kino.rank.sortBySimilarity`
     *   over `q`/`originalTitle`/`altTitles` against each match's title and original title, ties by
     *   TMDB popularity. It never calls `getStreams`: `resolve`/`episodes` do, with the id in the ref.
     *   Kino's `type` `"movie"` is NOT a restriction here: a typed search's card is always a movie
     *   (`freeTextCard`), so only `"series"` narrows it. A TMDB failure answers `[]`, never an error.
     * - `episodes` lists every season but 0 (specials, which Nuvio scrapers don't carry) from TMDB's
     *   `/tv/<id>` and `/tv/<id>/season/<n>`, fetched together, dropping episodes that haven't aired.
     * - `resolve` calls the wrapped `getStreams` exactly as Nuvio does: the id as a string, `"tv"`
     *   with the season and episode, or `"movie"` with `null, null` (never `0, 0`). Of the results that
     *   aren't torrent-only (Kino's sandbox has no BitTorrent client, spec §6.2) it picks by quality,
     *   read from `quality`/`title`/`name` whatever their type: 1080p, then 720p, then anything else,
     *   and 2160p/4K last (most TVs and phones here can't decode 4K HEVC); ties keep the scraper's
     *   order. It logs how many streams came back, how many were dropped (torrents, no url) and
     *   which quality it played. With nothing
     *   playable it says why, for [PluginFailureText]: `unavailable` [ONLY_TORRENTS], `unavailable`
     *   [SCRAPER_ERROR_PREFIX] + the scraper's first `console.error`, or `not_found` [NO_STREAMS].
     *
     * TMDB is asked in `es-MX` when Kino's language is Spanish (`kino.lang` is `es-CO`, for which TMDB
     * has almost no translations; the app's own TMDB client uses `es-MX` too), else in `kino.lang`.
     *
     * `ref` normally arrives as the JSON string this adapter built (Kino quotes an item's `ref` before
     * calling `resolve`/`episodes` with it -- see `PluginContentSource`), but a plain object is accepted
     * too. Refs saved before `episodes` existed (`{tmdbId, type, season: 0, episode: 0}`) still work.
     *
     * The media type is TRANSLATED, never passed through: Kino's `query.type` is
     * `"movie"`/`"series"`/`"any"` (`PluginContentSource.queryJson`), Nuvio's `getStreams` expects
     * `"movie"`/`"tv"` (its manifests' own `supportedTypes`). `"any"` is decided from the episode
     * fields: a season AND an episode mean a TV episode, anything else a movie.
     *
     * Every export starts with `await null`: a throw before an async function's first await aborts
     * the whole call in this engine (docs/plugins/README.md, "a rejection nobody is listening to yet").
     */
    private val ADAPTER = """

        var __nuvioGetStreams = __nuvioModuleExports.getStreams;
        var __NUVIO_TMDB_API = "https://api.themoviedb.org/3";
        var __NUVIO_TMDB_IMAGES = "https://image.tmdb.org/t/p/";
        var __NUVIO_ARTWORK_TIMEOUT_MS = 4000;
        var __NUVIO_TEXT_SEARCH_TIMEOUT_MS = 8000;
        var __NUVIO_TEXT_SEARCH_MAX = 10;

        function __nuvioMediaType(type, season, episode) {
          if (type === "series" || type === "tv") return "tv";
          if (type === "movie") return "movie";
          return (season > 0 && episode > 0) ? "tv" : "movie";
        }

        // Nuvio's supportedTypes, already folded onto movie / tv / anime (NuvioMediaTypes). Anime alone covers films and shows; unknown or
        // empty keeps every type.
        function __nuvioSupports(mediaType) {
          var t = __NUVIO_SUPPORTED_TYPES;
          var known = t.filter(function (x) { return x === "movie" || x === "tv" || x === "anime"; });
          if (!known.length || known.indexOf("anime") >= 0) return true;
          return known.indexOf(mediaType) >= 0;
        }

        function __nuvioUnsupported(mediaType) {
          return kino.error("unavailable", __NUVIO_SCRAPER_NAME + (mediaType === "tv" ? " no tiene series" : " no tiene películas"));
        }

        function __nuvioRef(ref) { return (typeof ref === "string") ? JSON.parse(ref) : ref; }

        // A stream's quality label from Nuvio's quality/title/name, whatever a scraper put there.
        function __nuvioQualityText(s) {
          return [s.quality, s.title, s.name].map(function (v) {
            try { return (v === null || v === undefined) ? "" : String(v); } catch (e) { return ""; }
          }).join(" ").toLowerCase();
        }

        // 0 = 1080p, 1 = 720p, 2 = anything else, 3 = 2160p/4K (most devices here can't decode 4K HEVC).
        function __nuvioQualityRank(s) {
          var t = __nuvioQualityText(s);
          if (/(^|[^a-z0-9])(2160p?|4k|uhd)([^a-z0-9]|$)/.test(t)) return 3;
          if (/(^|[^a-z0-9])(1080p?|fhd|full ?hd)([^a-z0-9]|$)/.test(t)) return 0;
          if (/(^|[^a-z0-9])720p?([^a-z0-9]|$)/.test(t)) return 1;
          return 2;
        }

        var __NUVIO_QUALITY_NAMES = ["1080p", "720p", "other", "4K"];

        // The best of the playable streams by that rank; ties keep the scraper's own order.
        function __nuvioPick(playable) {
          var best = playable[0], bestRank = __nuvioQualityRank(best);
          for (var i = 1; i < playable.length; i++) {
            var r = __nuvioQualityRank(playable[i]);
            if (r < bestRank) { best = playable[i]; bestRank = r; }
          }
          return { stream: best, rank: bestRank };
        }

        function __nuvioTmdbLanguage() {
          var lang = String(kino.lang || "");
          return lang.toLowerCase().indexOf("es") === 0 ? "es-MX" : (lang || "en-US");
        }

        async function __nuvioTmdb(path, timeoutMs, params) {
          var opts = { headers: { Accept: "application/json" } };
          if (timeoutMs) opts.timeoutMs = timeoutMs;
          var r = await kino.fetch(__NUVIO_TMDB_API + path + "?api_key=" + encodeURIComponent(__NUVIO_TMDB_KEY) +
            "&language=" + encodeURIComponent(__nuvioTmdbLanguage()) + (params || ""), opts);
          if (!r.ok) throw kino.error(r.status === 404 ? "not_found" : "unavailable", "TMDB respondió " + r.status);
          return r.json();
        }

        function __nuvioImage(size, path) { return path ? __NUVIO_TMDB_IMAGES + size + path : undefined; }

        function __nuvioYear(date) { return (typeof date === "string" && date.length >= 4) ? date.slice(0, 4) : undefined; }

        // A typed search (no TMDB id): TMDB's own search, one request, never getStreams. See the KDoc.
        async function __nuvioTextSearch(query) {
          var q = String(query.q || "").trim();
          if (!q) return [];
          var season = query.season || 0, episode = query.episode || 0;
          var kinds = (query.type === "series" ? ["tv"] : ["movie", "tv"]).filter(__nuvioSupports);
          if (!kinds.length) return [];
          var path = kinds.length > 1 ? "/search/multi" : "/search/" + kinds[0];
          var body;
          try {
            body = await __nuvioTmdb(path, __NUVIO_TEXT_SEARCH_TIMEOUT_MS, "&query=" + encodeURIComponent(q) + "&include_adult=false&page=1");
          } catch (e) {
            console.log("[Kino] TMDB search failed: " + (e && e.message ? e.message : String(e)));
            return [];
          }
          var results = (body && Array.isArray(body.results)) ? body.results : [];
          var matches = [];
          results.forEach(function (m) {
            if (!m || typeof m.id !== "number" || m.id <= 0) return;
            var mediaType = kinds.length > 1 ? m.media_type : kinds[0];
            if (kinds.indexOf(mediaType) < 0) return;
            var title = mediaType === "movie" ? (m.title || m.original_title) : (m.name || m.original_name);
            if (!title) return;
            var original = mediaType === "movie" ? m.original_title : m.original_name;
            matches.push({ m: m, mediaType: mediaType, title: String(title), original: original ? String(original) : "" });
          });
          matches.sort(function (a, b) { return (Number(b.m.popularity) || 0) - (Number(a.m.popularity) || 0); });
          var forms = [q, query.originalTitle].concat(Array.isArray(query.altTitles) ? query.altTitles : [])
            .filter(function (t) { return typeof t === "string" && t.trim().length > 0; });
          matches = kino.rank.sortBySimilarity(matches, forms, function (x) { return [x.title, x.original]; });
          return matches.slice(0, __NUVIO_TEXT_SEARCH_MAX).map(function (x) {
            var m = x.m, id = m.id;
            var art = {
              year: __nuvioYear(m.release_date || m.first_air_date),
              poster: __nuvioImage("w500", m.poster_path),
              backdrop: __nuvioImage("w1280", m.backdrop_path),
              overview: m.overview || undefined,
            };
            if (x.mediaType === "tv" && !(season > 0 && episode > 0)) {
              return Object.assign({
                id: id + "-series", ref: JSON.stringify({ tmdbId: id, type: "tv" }),
                title: x.title, kind: "series", ids: { tmdb: id },
              }, art);
            }
            var type = x.mediaType === "tv" ? "series" : "movie";
            var item = Object.assign({
              id: id + "-" + type + "-" + season + "-" + episode,
              ref: JSON.stringify({ tmdbId: id, type: type, season: x.mediaType === "tv" ? season : 0, episode: x.mediaType === "tv" ? episode : 0 }),
              title: x.title, kind: "movie",
            }, art);
            if (x.mediaType === "movie") {
              item.id = id + "-movie-0-0";
              item.ids = { tmdb: id };
            }
            return item;
          });
        }

        export async function search(query) {
          await null;
          if (!query.tmdbId) return __nuvioTextSearch(query);
          var season = query.season || 0, episode = query.episode || 0;
          var mediaType = __nuvioMediaType(query.type, season, episode);
          if (!__nuvioSupports(mediaType)) return [];
          var meta = null;
          try { meta = await __nuvioTmdb("/" + mediaType + "/" + query.tmdbId, __NUVIO_ARTWORK_TIMEOUT_MS); } catch (e) { meta = null; }
          var m = meta || {};
          var title = query.q || query.originalTitle || m.title || m.name || "";
          var art = {
            year: __nuvioYear(m.release_date || m.first_air_date),
            poster: __nuvioImage("w500", m.poster_path),
            backdrop: __nuvioImage("w1280", m.backdrop_path),
            overview: m.overview || undefined,
          };
          if (mediaType === "tv" && !(season > 0 && episode > 0)) {
            return [Object.assign({
              id: query.tmdbId + "-series",
              ref: JSON.stringify({ tmdbId: query.tmdbId, type: "tv" }),
              title: title, kind: "series", ids: { tmdb: query.tmdbId },
            }, art)];
          }
          var item = Object.assign({
            id: query.tmdbId + "-" + query.type + "-" + season + "-" + episode,
            ref: JSON.stringify({ tmdbId: query.tmdbId, type: query.type, season: season, episode: episode }),
            title: title, kind: "movie",
          }, art);
          if (mediaType === "movie") item.ids = { tmdb: query.tmdbId };
          return [item];
        }

        export async function episodes(ref) {
          await null;
          var r = __nuvioRef(ref);
          if (!__nuvioSupports("tv")) throw __nuvioUnsupported("tv");
          var show = await __nuvioTmdb("/tv/" + r.tmdbId);
          var numbers = (show.seasons || []).map(function (s) { return s.season_number; })
            .filter(function (n) { return typeof n === "number" && n > 0; });
          var seasons = await Promise.all(numbers.map(function (n) {
            return __nuvioTmdb("/tv/" + r.tmdbId + "/season/" + n).catch(function () { return null; });
          }));
          var today = new Date().toISOString().slice(0, 10);
          var list = [];
          seasons.forEach(function (s, i) {
            if (!s) return;
            (s.episodes || []).forEach(function (e) {
              if (typeof e.episode_number !== "number" || e.episode_number < 1) return;
              if (e.air_date && e.air_date > today) return;
              list.push({
                season: numbers[i], number: e.episode_number,
                ref: JSON.stringify({ tmdbId: r.tmdbId, type: "tv", season: numbers[i], episode: e.episode_number }),
                title: e.name || undefined, still: __nuvioImage("w300", e.still_path), overview: e.overview || undefined,
                airDate: e.air_date || undefined, runtimeMinutes: e.runtime || undefined,
              });
            });
          });
          if (numbers.length && !seasons.some(function (s) { return s; })) throw kino.error("unavailable", "TMDB no dio ninguna temporada");
          return {
            series: {
              title: show.name || undefined, poster: __nuvioImage("w500", show.poster_path),
              backdrop: __nuvioImage("w1280", show.backdrop_path), overview: show.overview || undefined,
              ids: { tmdb: r.tmdbId }, year: __nuvioYear(show.first_air_date),
              genres: (show.genres || []).map(function (g) { return g.name; }).filter(Boolean),
            },
            episodes: list,
          };
        }

        export async function resolve(ref) {
          await null;
          var r = __nuvioRef(ref);
          var mediaType = __nuvioMediaType(r.type, r.season, r.episode);
          if (!__nuvioSupports(mediaType)) throw __nuvioUnsupported(mediaType);
          if (mediaType === "tv" && !(r.season > 0 && r.episode > 0)) throw kino.error("not_found", "falta elegir temporada y capítulo");
          var season = mediaType === "tv" ? r.season : null;
          var episode = mediaType === "tv" ? r.episode : null;
          __nuvioConsole.errors.length = 0;
          var streams = (await __nuvioGetStreams(String(r.tmdbId), mediaType, season, episode)) || [];
          if (!Array.isArray(streams)) streams = [];
          var torrents = streams.filter(function (s) { return s && s.infoHash; }).length;
          var noUrl = streams.filter(function (s) { return s && !s.infoHash && !s.url; }).length;
          var playable = streams.filter(function (s) { return s && s.url && !s.infoHash; });
          var choice = playable.length ? __nuvioPick(playable) : null;
          var picked = choice ? String(choice.stream.url).replace(/^[a-z]+:\/\/([^\/?#]*).*$/i, "$1") +
            " (" + __NUVIO_QUALITY_NAMES[choice.rank] + " of " + playable.length + " playable)" : "nothing";
          console.log("[Kino] getStreams returned " + streams.length + " streams; dropped " + torrents +
            (torrents === 1 ? " torrent, " : " torrents, ") + noUrl + " without url; playing " + picked);
          if (!playable.length) {
            if (torrents > 0) throw kino.error("unavailable", "$ONLY_TORRENTS");
            var said = __nuvioConsole.errors[0];
            if (said) throw kino.error("unavailable", "$SCRAPER_ERROR_PREFIX" + said);
            throw kino.error("not_found", "$NO_STREAMS");
          }
          var best = choice.stream;
          return { url: best.url, headers: best.headers, mime: best.mime };
        }
    """.trimIndent()

    /**
     * The `console` the scraper's code sees: the sandbox's own, plus a record of what it passed to
     * `console.error` since the adapter last cleared it. Nuvio scrapers catch their own failures,
     * `console.error` them and return `[]`; that first error is the reason `resolve` reports (cut,
     * its "[Name] Error in getStreams:" prefix dropped) when nothing is playable.
     */
    private val CONSOLE = """
        var __nuvioConsole = (function () {
          var errors = [];
          function text(args) {
            return Array.prototype.map.call(args, function (a) {
              try { return (a && a.message) ? String(a.message) : String(a); } catch (e) { return "?"; }
            }).join(" ");
          }
          return {
            errors: errors,
            log: function () { return console.log.apply(console, arguments); },
            info: function () { return console.info.apply(console, arguments); },
            warn: function () { return console.warn.apply(console, arguments); },
            debug: function () { return console.log.apply(console, arguments); },
            error: function () {
              if (errors.length < 5) {
                var t = text(arguments).replace(/^\s*\[[^\]]*\]\s*/, "").replace(/^Error in getStreams:\s*/i, "").trim();
                if (t) errors.push(t.slice(0, 120));
              }
              return console.error.apply(console, arguments);
            },
          };
        })();

    """.trimIndent() + "\n"

    /** `resolve`'s `not_found` detail: the scraper answered, with no stream at all. */
    const val NO_STREAMS = "sin resultados"

    /** `resolve`'s `unavailable` detail: every stream was a torrent, which Kino can't play. */
    const val ONLY_TORRENTS = "solo torrents"

    /** `resolve`'s `unavailable` detail prefix: nothing playable, and the scraper `console.error`ed why. */
    const val SCRAPER_ERROR_PREFIX = "error del scraper: "
}

/**
 * Works around our QuickJS build (quickjs-kt 1.0.0-alpha13) aborting the WHOLE call when a promise
 * is rejected before anything handles it, even if a `try`/`catch` would catch it a moment later
 * (fixed upstream in quickjs-kt 1.0.1, which needs Kotlin 2.3; see docs/plugins/README.md, "The
 * trap"). A transpiled `async` function hits it all the time: the transpilers' helpers run the
 * body's first step synchronously inside the `Promise` executor, so a `throw` before the first
 * `await` rejects before the caller's `await` has attached its handler.
 *
 * [defer] moves that first step one microtask later in the helpers bundlers emit -- esbuild's
 * `__async` (plain and minified), TypeScript's `__awaiter` (plain and minified) and Babel's
 * `_asyncToGenerator` -- so the caller is listening by the time the body can throw. Each pattern is
 * anchored on the helper's own `Promise` constructor and its first-step call; a source without one
 * comes back untouched. Native `async` functions have nothing to rewrite.
 */
internal object NuvioAsyncStart {
    private const val ID = """[\w$]+"""

    /**
     * esbuild: `new Promise((resolve, reject) => { ... step((generator = generator.apply(__this, __arguments)).next()); })`,
     * minified `new Promise((c,a)=>{...n((e=e.apply(o,s)).next())})`.
     */
    private val ESBUILD = Regex(
        """(new Promise\(\(\s*$ID\s*,\s*($ID)\s*\)\s*=>\s*\{)((?:(?!new Promise)[\s\S]){0,800}?)""" +
            """($ID)\(\(($ID)\s*=\s*\5\.apply\(\s*($ID)\s*,\s*($ID)\s*\)\)\.next\(\)\)""",
    )

    /**
     * TypeScript/tslib: `new (P || (P = Promise))(function (resolve, reject) { ... step((generator = generator.apply(thisArg, _arguments || [])).next()); })`,
     * minified `new(n||(n=Promise))(function(o,i){...c((r=r.apply(e,t||[])).next())})`.
     */
    private val TYPESCRIPT = Regex(
        """(new\s*\(\s*($ID)\s*\|\|\s*\(\s*\2\s*=\s*Promise\s*\)\s*\)\s*\(\s*function\s*\(\s*$ID\s*,\s*($ID)\s*\)\s*\{)""" +
            """((?:(?!new\s*\()[\s\S]){0,1000}?)""" +
            """($ID)\(\(($ID)\s*=\s*\6\.apply\(\s*($ID\s*,\s*$ID(?:\s*\|\|\s*\[\s*\])?)\s*\)\)\.next\(\)\)""",
    )

    /**
     * Babel: `function _asyncToGenerator(fn) { ... new Promise(function (resolve, reject) { ... _next(undefined); }) }`
     * (`_next(void 0)` in newer Babel). Its step already catches a throw and rejects, so it needs no `.catch`.
     */
    private val BABEL = Regex(
        """(function\s+_asyncToGenerator\s*\(\s*$ID\s*\)\s*\{(?:(?!function\s+_asyncToGenerator)[\s\S]){0,800}?)\b_next\((void 0|undefined)\)""",
    )

    fun defer(source: String): String {
        var out = source
        if ("new Promise" in out) {
            out = ESBUILD.replace(out) { m ->
                val g = m.groupValues
                "${g[1]}${g[3]}Promise.resolve().then(() => ${g[4]}((${g[5]} = ${g[5]}.apply(${g[6]}, ${g[7]})).next())).catch(${g[2]})"
            }
        }
        if ("Promise))" in out) {
            out = TYPESCRIPT.replace(out) { m ->
                val g = m.groupValues
                "${g[1]}${g[4]}Promise.resolve().then(function () { ${g[5]}((${g[6]} = ${g[6]}.apply(${g[7]})).next()); }).catch(${g[3]})"
            }
        }
        if ("_asyncToGenerator" in out) {
            out = BABEL.replace(out) { m ->
                val g = m.groupValues
                "${g[1]}Promise.resolve().then(function () { _next(${g[2]}); })"
            }
        }
        return out
    }
}
